### ISSUE TITLE
Reading Vatic Annotations

### ISSUE THREAD

**Issue by pulkitag** [pulkitag/chainer#4]
Create a chain object for this.

**Comment by gnetscher** [comment]
write script to:
want to be able to pull out image names with bounding box labels and coordinates 
try using vatic built in command to create pickle file
look in vatic directory: cli.py. dumppickle
convert_pascal script in vatic/vatic/

**Comment by gnetscher** [comment]
finished and merged

**Comment by pulkitag** [comment]
Thats great! Let me know when you have the mAP thing - we can then get the results.
